### ISSUE TITLE
kernel installer only installs the base package 

### ISSUE THREAD

**Issue by sanchitsamuel** [manjaro/manjaro-settings-manager#103]
When installing the new kernel, lets say moving from _4.10_ to _4.11_, it only install the **linux411** package, and skips all the other modules installed with _4.10_ like **linux410-headers** or **linux410-tp_smapi** or **linux410-vbox-host-modules**
This gives a bad user experience, when you have to manually go and install those packages. :)

**Comment by philmmanjaro** [comment]
**mhwd-kernel** has this feature to install also its extramodules when the current running kernel has some. I assumed we have ported that feature also to **msm**.
