### ISSUE TITLE
[Keyboard] Support configuration of multiple keyboards

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-settings-manager#11]
We only support configuration with a single keyboard mapping, we need to detect and provide an interface to configure multiple keyboards

**Comment by georoot** [comment]
Would it be possible to use results from `xinput list` and get all available keyboards from there itself ?

**Comment by philmmanjaro** [comment]
Possible. Ramon, what do you think about that?

**Comment by georoot** [comment]
i did write the codes to read content from /dev/input/event0 or any interface for that matter.and xinput to get list of all keyboard interfaces

**Comment by philmmanjaro** [comment]
Fine. Edit it on your end and we review the code. Remember that **master** and **0.4.x** use different stage of code. You might need to backport your **master** commit to our stable branch ...

**Comment by Kirek** [comment]
Whatever works for this is fine :)

**Comment by georoot** [comment]
hi please checkout this code . it caould be used to find the device name and its file path. https://gist.github.com/cab3b620b7cfacbe3b15 . Now the problem i am facing is i am not too comfortable with Qt , so can you help me out with how to integrate this in the existing codebase. After this i was thinking in the lines of using setxkbmap to ket the keyboard map for each one diffrently.
