### ISSUE TITLE
Automatic time shall be applicable

### ISSUE THREAD

**Issue by es20490446e** [manjaro/manjaro-settings-manager#111]
HOW TO REPRODUCE:
1. Go to "Manjaro Settings Manager -> Time and Date".
2. Mark the option "set time and date automatically".

RESULT:
- The "apply" button stays greyed out, where it should be activated.
- Even better if the option was enabled without needing to press any "apply" button at all.

**Comment by jhrdina** [comment]
I tried the obvious solution to add

```c++
this -> setApplyEnabled( this, true );
```
below line https://github.com/manjaro/manjaro-settings-manager/blob/a0272302536cb028a892f68d610256c4b83ed0eb/src/modules/timedate/TimeDatePage.cpp#L54

Unfortunately it seems like one extra `toggled` event is fired on msm startup, as this fix causes the following awkward behavior:

1. Go to "Manjaro Settings Manager -> Time and Date", _the "apply" button is enabled (it shouldn't)_
2. Go back to main screen
3. Open "Time and Date" again, _the "apply" button is disabled (as it should be)_

**Comment by scachemaille** [comment]
you can try to modify this part in TimeDateCommon.cpp ?
https://github.com/manjaro/manjaro-settings-manager/blob/a0272302536cb028a892f68d610256c4b83ed0eb/src/modules/timedate/TimeDateCommon.cpp#L94
to
```
if ( timeDateService->canNtp() )
{
    ui->isNtpEnabledCheckBox->blockSignals( true );
    ui->isNtpEnabledCheckBox->setChecked( timeDateService->isNtpEnabled() );
    ui->isNtpEnabledCheckBox->blockSignals( false );
}
```

**Comment by es20490446e** [comment]
Okay. Added to my todo list.

**Comment by jhrdina** [comment]
I've tested the non-kde version used in XFCE and everything seems to be working in 0.5.4-7 from unstable: Apply button gets enabled properly and time/date textfields are also enabled/disabled as they should.

**Comment by es20490446e** [comment]
Works in KDE too.
