### ISSUE TITLE
Hi Res Scrunched

### ISSUE THREAD

**Issue by nyrosis** [manjaro/manjaro-settings-manager#112]
My platform is a Lenovo Yoga 2 with intel graphics.  Manjaro Gnome was installed on this device.
I believe manjaro-settings-manager is not rendering as intended on high resolution displays. I have provided 2 screenshots.

Although everything is scrunched it still performs as expected.  This just seems to be a rendering problem on high resolution displays.

![screenshot from 2017-07-22 22-19-24](https://user-images.githubusercontent.com/30380117/28495974-d0e5f952-6f2c-11e7-808c-4efe614a5de3.png)
![screenshot from 2017-07-22 22-20-24](https://user-images.githubusercontent.com/30380117/28495976-d863308c-6f2c-11e7-80ea-fbe9382c92cb.png)

**Comment by Kirek** [comment]
Should be fixed via https://github.com/manjaro/manjaro-settings-manager/commit/e7a9b99e6319ed42b2b0721fcc8fd6704bf870f7

Can you test the new build?
https://www.dropbox.com/s/n2iect17oyt34ro/manjaro-settings-manager-dev-0.5.4rc1-1-x86_64.pkg.tar.xz?dl=0
Install with `sudo pacman -U manjaro-settings-manager-dev-0.5.4rc1-1-x86_64.pkg.tar.xz`
