### ISSUE TITLE
[kernel module] window default size to small

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-settings-manager#115]
...or kernel font too large.
In any case longer kernel names like for example with 'rc' or 'rt' attributes end up partly covered by their own labels:

![kernel_module](https://user-images.githubusercontent.com/11800714/30036542-b786acfe-91b4-11e7-9fef-f34db598f696.png)

**Comment by oberon2007** [comment]
@Kirek @philmmanjaro

**Comment by oberon2007** [comment]
guys, we should really do something about it, it doesn't look good at all:
![screenshot_2017-09-12_05-51-39](https://user-images.githubusercontent.com/11800714/30319751-b5d32430-977e-11e7-9f80-aa73290f3fbb.png)
I'm afraid just changing minimum window size will not be enough. Very likely just the way those labels are positioned need to be changed and/or the fontsize for kernel names needs to be decreased ...

**Comment by philmmanjaro** [comment]
You may change the [factor](https://github.com/manjaro/manjaro-settings-manager/blob/master/src/modules/kernel/KernelListViewDelegate.cpp#L76) to a lower value and recompile the source. Tell me if that helps.

**Comment by Kirek** [comment]
Check https://github.com/manjaro/manjaro-settings-manager/commit/a0272302536cb028a892f68d610256c4b83ed0eb (the font size change has been reverted)

**Comment by oberon2007** [comment]
Love it @Kirek That's perfect, thank you!
