### ISSUE TITLE
m-s-n not aplly the default configurations

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-settings-manager#124]
@Kirek @philmmanjaro , this [commit](https://github.com/manjaro/manjaro-settings-manager/commit/e9500db6b43ec8d3104de3d6ccfb46d134ea47dc) introduce new default configs ( we have to add also in kde source version ( i have applied but the result is the same)) but seems m-s-n not respect this change.. se also report in the [forum](https://forum.manjaro.org/t/testing-update-2017-11-24-kernels-kdevelop-virtualbox/35354/2)  
Any ideas ?

**Comment by vfjpl** [comment]
What exacly do you mean? If you have made some change in the past to settings of the notifier then it will use your setting rather than default.

**Comment by philmmanjaro** [comment]
Please review **0.5.3-8** or higher.

**Comment by Ste74** [comment]
Right but for test it without build a new iso to test in vbox i have simply created another user and the default settings are not applied :p

**Comment by philmmanjaro** [comment]
Well, you forgot about the KDE version:

https://github.com/manjaro/manjaro-settings-manager/blob/master/src/notifier/notifier_kde/Notifier.cpp

**Comment by Ste74** [comment]
Yep , i have build my self for kde version but nothing change .. :p

**Comment by philmmanjaro** [comment]
@Ste74 please post a screenshot on how the checkboxes should be marked by default. @Kirek: can you double check why those don't apply. Then we might need to adjust both notifiers similar.

**Comment by vfjpl** [comment]
I Can confirm. No matter what is set in the code, ticks are always ticked the same(both normal and kde).

**Comment by Ste74** [comment]
I'm here.. is it what i want..
![m-s-n](https://user-images.githubusercontent.com/11218234/33575601-70ee8e80-d93d-11e7-9735-b3ede97f4527.png)

**Comment by philmmanjaro** [comment]
then we have to see where it get set. @Kirek: ideas? do we have an UI file I'm missing?

**Comment by Ste74** [comment]
I also try to find where in the $HOME/.config/manjaro folder is set the custom config and found it  but i not understand how the file have to be modified .. of course is a dirty workaround

**Comment by vfjpl** [comment]
It's weird bug because if the file with the config is set, then config if properly aplayed. 
I presume that QSettings settings( "manjaro", "manjaro-settings-manager" ); sets name of the config file. But I have tried changing manjaro-settings-manager to manjaro-settings-manager-Notifier but the config was still saving in manjaro-settings-manager.conf in ~/.config/manjaro

**Comment by philmmanjaro** [comment]
Ok, I think I found it now: https://github.com/manjaro/manjaro-settings-manager/blob/master/src/libmsm/NotifierSettingsDialog.cpp#L121

**Comment by philmmanjaro** [comment]
Please review **0.5.4-7** or higher.

**Comment by Ste74** [comment]
@philmmanjaro yeah 👍  .. perfect now work as expected 😉

**Comment by philmmanjaro** [comment]
Fine, so we may solve this then?

**Comment by Ste74** [comment]
Yep , only decide if use the patch or update the source 😉
