### ISSUE TITLE
manjaro-notifier : wrong message like unsupported kernel installed

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-settings-manager#134]
After the last change in m-n-s the default settings are right but now not understand why in gnome ISO warning me for not supported kernel installed. 
maybe this line ?
https://github.com/manjaro/manjaro-settings-manager/blob/master/src/libmsm/KernelModel.cpp#L370

**Comment by philmmanjaro** [comment]
The question is if you have a valid pacman DB. If not this might happen. So always sync the DB first before checking anything.

**Comment by Ste74** [comment]
Ahhhh. Right...
