### ISSUE TITLE
Adopt to new RT-Kernel Meta-Packages

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-settings-manager#135]
Since we are now using the new **meta-packages** we might either update their displaying or adopt to the new packages called `<linux4xx>-rt`

<img src="https://forum.manjaro.org/uploads/default/optimized/3X/d/c/dc0a9cd8c179e920d07cfca249dd5b8752a1cd2c_1_650x500.png">

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/mhwd/commit/e5c31e663305f034ffa51f715c0a3d4175b5b930
https://github.com/manjaro/manjaro-settings-manager/commit/c6ce83561307e87171a283f30d6f5faa085fba5e
https://github.com/manjaro/manjaro-settings-manager/commit/dff3d3ba610e501ba0b2308c7ec1a31e74e23ce8

**Comment by oberon2007** [comment]
Oh! Didn't think of that! 😉

**Comment by philmmanjaro** [comment]
It should now work as intended. I assume the new **linux-rt-manjaro** will be then **linux415-rt**, **linux416-rt** and so on ...

**Comment by oberon2007** [comment]
Exactly that, thank you.
Seems to be working fine.
