### ISSUE TITLE
Segfault on opening Manjaro Settings Manager

### ISSUE THREAD

**Issue by Pratham25** [manjaro/manjaro-settings-manager#146]
I have a very weird issue going on here:
When I open manjaro settings manager from menu, nothing happens. In terminal, it shows: 5715 segmentation fault (core dumped)  manjaro-settings-manager. If I prefix sudo, it works fine but without any gtk theme and if I prefix pkexec it says that it can't connect too the X display. I have reinstalled to no avail. I have a similar problem with the notifier.

**Comment by scachemaille** [comment]
you should not call it with sudo or pkexec anyway.. it does not have to be run as root.
is your system up to date? does other QT software works?

**Comment by Pratham25** [comment]
@scachemaille System up to date, and now that I check, qbittorrent also throws up segfaults

**Comment by scachemaille** [comment]
then it's certainly related with qt5ct, qt5-styleplugins and all the settings for QT under GTK DE.
I'm not a specialist for that. you should as on forum.
I will close the issue for now.
