### ISSUE TITLE
msm is inaccessible with orca

### ISSUE THREAD

**Issue by coffeeking** [manjaro/manjaro-settings-manager#18]
as far back as I can remember, manjaro-settings-manager has not been accessible with orca, the screen reader. It's written in qt, so this definitely is possible. I'm not at all sure how to fix this, but qt apps are not hard to make accessible with orca. Maybe declaring the area where all the icons are an icon pane? As long as the roll is set correctly, meaning a list is set up as a list, orca should read it fine, assuming no custom widgets are used. If they are, then they need accessible labels attached to them. Sorry, just trying to give as much information as I can.

**Comment by Kirek** [comment]
This should be fixed now that msm doesn't require admin rights to run.
