### ISSUE TITLE
Clicking the Hyperlinks in the text session...

### ISSUE THREAD

**Issue by Lukimya** [manjaro/manjaro-settings-manager#21]
...Cause the settings manager to crash very often. Should this not be a known problem I hereby declare it to be one.

**Comment by philmmanjaro** [comment]
I assume you mean the kernel informations were we use our internal browser? I just tested that and it works. Please open MSM from a terminal and post any output you may find.

**Comment by Lukimya** [comment]
● zatox@zatox ~] manjaro-settings-manager
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed


It gives me that error when i start it. but it starts. when it crashes it does not give anything. I dont understand it.

**Comment by Kirek** [comment]
start it with "sudo manjaro-settings-manager-gui"

**Comment by Lukimya** [comment]
It does not produce any error message. I cant produce the crash as often as couple of days ago, but it still occurs.
