### ISSUE TITLE
Use libnotify instead of these XP-Style notification bubbles

### ISSUE THREAD

**Issue by vincent-t** [manjaro/manjaro-settings-manager#24]
At the moment manjaro-settings-manager uses these "ugly" notification bubbles. Instead of these bubbles you should use notifications which look better because they can be themed.

**Comment by georoot** [comment]
@Kirek  i think i can handle this one. Just for a confirmation i should be changing over the codes at notifier right?

**Comment by Kirek** [comment]
Yes, fell free to modify anything under that.

**Comment by Kirek** [comment]
Solved by using KStatusNotifierItem for notifications
