### ISSUE TITLE
Comment about systemd-localed in /etc/X11/xorg.conf.d/00-keyboard.conf after setting keyboard layout using MSM

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/manjaro-settings-manager#25]
Would it be possible to remove this comment?

~~~~
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
~~~~
https://github.com/manjaro/manjaro-settings-manager/blob/master/src/modules/keyboard/SetKeyboardLayoutJob.cpp#L169

**Comment by Kirek** [comment]
https://github.com/manjaro/manjaro-settings-manager/commit/ccb05b84666ee325d059653feae1817f880e7225
