### ISSUE TITLE
Color escape codes are shown when installing video drivers

### ISSUE THREAD

**Issue by 4Evergreen4** [manjaro/manjaro-settings-manager#26]
When I update graphics drivers, instead of displaying the actual colours, it just shows the colour's escape code.

Screenshot:

![Color codes shown](https://lut.im/BFzUv9yN/QO9lxa63)

The colours do work properly when `mhwd` is run from the terminal.

**Comment by Kirek** [comment]
Fixed https://github.com/manjaro/manjaro-settings-manager/commit/d389b11b76eddd6cb9a096466853e5597a2028d3

**Comment by philmmanjaro** [comment]
Do we backport this also to 0.4.x?

**Comment by Kirek** [comment]
Yes, we should
