### ISSUE TITLE
Can not start (Segmentation fault)

### ISSUE THREAD

**Issue by ghost** [manjaro/manjaro-settings-manager#31]
```$ pkexec manjaro-settings-manager-gui```
```Segmentation fault (core dumped)```

And

```$ sudo manjaro-settings-manager```
```/usr/bin/manjaro-settings-manager: line 14:  1415 Segmentation fault      (core dumped) pkexec "$PROGRAM" "$@"```

**Comment by philmmanjaro** [comment]
Works here. Do you have any polkit agent running?

```
[phil@manjaro ~]$ pkexec manjaro-settings-manager-gui
[phil@manjaro ~]$ ps -ef | grep kit
polkitd    561     1  0 06:46 ?        00:00:00 /usr/lib/polkit-1/polkitd --no-debug
phil      1026   835  0 06:47 ?        00:00:00 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
rtkit     1071     1  0 06:47 ?        00:00:00 /usr/lib/rtkit/rtkit-daemon
phil     10397 10366  0 07:50 pts/1    00:00:00 grep --colour=auto kit
```

**Comment by dotMdot** [comment]
```[steve@Asus ~]$ pkexec manjaro-settings-manager-gui```
```Addressing error (screenshot saved RAM)```
```[steve@Asus ~]$ ps -ef | grep kit```
```polkitd      484     1  0 20:45 ?        00:00:00 /usr/lib/polkit-1/polkitd --no-debug```
```steve        815   755  0 20:47 tty2     00:00:00 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1```
```rtkit          824     1  0 20:47 ?        00:00:00 /usr/lib/rtkit/rtkit-daemon```
```steve       2723  2697  0 21:51 pts/1    00:00:00 grep --colour=auto kit```
