### ISSUE TITLE
Kernel Module: Be smarter when the pacman database is missing or outdated

### ISSUE THREAD

**Issue by ghost** [manjaro/manjaro-settings-manager#35]
hi , i see pamac of what ever messed a bit with the DB pacman, i dont know what it was 

but then i get :+1: 

http://i.imgur.com/5YvqHa4.png

its because DB is bit messed i notice, pacman -Syy  fixed the thing i notice. but on translation  
for Not supported is bit messed up.. i think i hear further those confusion like not supported..

but its likely more that the database not synced properly 

after pacman -Syy

i get this :+1: 

http://i.imgur.com/dUur2cz.png

thats better, i know is something on pamac , have to see further on that before i fill :)

on matter, i see its status of te repo, the middle line.. but some users seems also read different..
I would say, Auto-sync option if the kernel module not see not more then 3 kernels. i mean online...

To suppose to act bit smarter... not supported  some people read different.. but  the middle line is not what they mean.. but i would say atmeast auto-sync feature to the database because if database bit messed up or what ever happend kernels dont show up as it should..
Then it said not supported. but is a minor not direct a issue only i see some here and there people talk about that. but issuie is more the mirror sync.

**Comment by Kirek** [comment]
Yes, I suppose msm should be a little smarter when the databases are missing or outdated, and prompt the user to update them.

**Comment by Kirek** [comment]
Fixed https://github.com/manjaro/manjaro-settings-manager/commit/c3be96d6610c39056488a2a1ef85be12ee635a64
