### ISSUE TITLE
New slovak translation

### ISSUE THREAD

**Issue by prescott66** [manjaro/manjaro-settings-manager#36]
Hi.
I have checked a slovak translation on Transifex, but it is totally bad and i cant fix reviewed strings.
So i have created totally new one and correct, but Transifex preserves reviewed stringsm that are broken.
How can i upload my new fixed translation?

Here is the translation on my google drive, if you have some time, you can merge it:

https://drive.google.com/file/d/0B7IVEEF2578rZXNvY2t1ZktCN3c/view?usp=sharing

Thanks for help!

**Comment by philmmanjaro** [comment]
All translations can been found [here](https://www.transifex.com/manjarolinux/manjaro-settings-manager/dashboard/).

**Comment by prescott66** [comment]
Transifex:
Error:You are not allowed to edit a reviewed string.

**Comment by philmmanjaro** [comment]
@prescott66 try again ...

**Comment by prescott66** [comment]
Working! Thank you!
