### ISSUE TITLE
Manjaro Settings Manager pesters about missing language packs even though notifications disabled

### ISSUE THREAD

**Issue by geckolinux** [manjaro/manjaro-settings-manager#38]
Hi, 

in the Manjaro Settings Manager I have disabled all notifications about kernels and language packs. However, it continues to pester me about missing language packs every time I log in. 

Thanks for looking into this!

**Comment by philmmanjaro** [comment]
Which language packs does **MSM** suggest to get installed?

**Comment by sb56637** [comment]
Gimp help translations.

**Comment by philmmanjaro** [comment]
For which language?

**Comment by sb56637** [comment]
Spanish es_MX.
