### ISSUE TITLE
SES label is actually ESS (extended stable support)

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-settings-manager#46]
Seems there is a mixup with the label for extended stable supported kernels ...
```
Linux X.X.y-ckt extended stable support
```

**Comment by Kirek** [comment]
Ok, then let's rename it then.

**Comment by Kirek** [comment]
https://github.com/manjaro/manjaro-settings-manager/commit/89e531e9f0794d6efcaa92d8901c157f30bd2155

**Comment by philmmanjaro** [comment]
**linux42** can be tagged also as **ESS**

**Comment by philmmanjaro** [comment]
Ah, ok. already done ...

**Comment by philmmanjaro** [comment]
Just to mention. It was renamed from ESS to SES with be4a9d17c2a9c4fc1a77c5d5c3665fdf34f2041b

**Comment by Kirek** [comment]
Because you announced them as SES in the forums :)

**Comment by philmmanjaro** [comment]
Hmm. For reals? Let me check that ...

**Comment by philmmanjaro** [comment]
Found it. My bad then ...
```
Hi community, we already know that linux312 will be dropped soon by upstream. Greg will still maintain linux34 and linux310 almost thru 2014. Same does Canonical with their SES kernels (stable extended support). Now I need from our community to know which of these kernels are still needed and which of them I can drop. 
```
Will fix that in the forum now ...
