### ISSUE TITLE
Primary user group hardcoded to "users"

### ISSUE THREAD

**Issue by scachemaille** [manjaro/manjaro-settings-manager#47]
when we create a new user with the manjaro settings manager, it don't follow the settings 
of USERGROUPS_ENAB in /etc/login.defs and always specify "users" as primary group.

in /src/modules/users/AddUserDialog.cpp
`<args["arguments"] = QStringList() << "-m" << "-p" << "" << "-g" << "users" << "-G" << DEFAULT_USER_GROUPS << username;>`

That seems not consistent because since Manjaro 15.12 the installer create and set the primary group with the same name as the login name for the default user.

more details here:
[manjaro forum](https://forum.manjaro.org/index.php?topic=30145.0)

**Comment by Kirek** [comment]
Thanks for reporting, this should fix it.

**Comment by scachemaille** [comment]
you're welcome...
I added a comment on the master branch commit, as I'm not sure the -U option is the best solution
best regards
