### ISSUE TITLE
Clicking on Qt icon on notification area makes xfce panel flicker, when in Intelligent Hide

### ISSUE THREAD

**Issue by petsam** [manjaro/manjaro-settings-manager#50]
When I click on the msm icon at the notification area of the xfce panel, the panel starts flickering. The flickering stops only when changing focus (clicking desktop or another window).
This is happening only with the specific icon, not with the rest.
I tried many themes, WMs, and still happens.
See the forum topic for more https://forum.manjaro.org/index.php?topic=30213.0

**Comment by philmmanjaro** [comment]
Can you make a screencast from it and give us the exact package version so we can check.

**Comment by petsam** [comment]
If you check the link in my initial post you 'll see a gif animation and the configuration I had (xfce). Right now I have changed my configuration, run LMDE with Compiz and I don't have the issue.

**Comment by petsam** [comment]
I just connected this issue to the Qt framework (I think).
I opened a  [topic in the Manjaro Forum](https://forum.manjaro.org/t/flickering-panel-on-click-notification-area-qt-icons-intel/3810). I hope something will come up to close this or correct the description.

**Comment by petsam** [comment]
Update: I narrowed down this issue to the Intelligent Hide function of the panel and Qt systray icons. When the panel is set to "Always visible" or "Always hide" the issue does not happen.
There are some [XFCE bugs](https://bugzilla.xfce.org/buglist.cgi?quicksearch=intelligent) related to the intelligent hide feature of the xfce4-panel which points this is an xfce4 bug.

**Comment by Kurtoid** [comment]
This is a compiz bug

**Comment by GlebWork** [comment]
Just to mention it - Ubuntu fixed that one on their side, because they maybe **care** about their users. Maybe you can, develop patch to fix that issue? xfce is one of your default DE, and it has that bug out-of-box. Thank you.
