### ISSUE TITLE
Kernel 4.4.x LTS?

### ISSUE THREAD

**Issue by Gormogon** [manjaro/manjaro-settings-manager#51]
Why is the 4.4.x release being marked as LTS and recommended?  Does the Manjaro team plan to support this long-term?  As far as I'm aware it's just a stable release and probably shouldn't be recommended to users...

https://www.kernel.org/

**Comment by Kirek** [comment]
It was announced months ago:
https://plus.google.com/+gregkroahhartman/posts/WMEWz4noxFm

**Comment by Gormogon** [comment]
@Kirek Thanks for the quick response.

Wow. Indeed it was. I was only going by what was posted on kernel.org.  Closing issue.
