### ISSUE TITLE
[Hardware detection] Intel HD Graphics 5500 - unknown device name

### ISSUE THREAD

**Issue by artur9010** [manjaro/manjaro-settings-manager#55]
![screenshot_20160328_123601](https://cloud.githubusercontent.com/assets/4835677/14076416/b63dce84-f4e1-11e5-8830-4c4811942e19.png)

**Comment by Kirek** [comment]
msm gets that information from hwinfo, if it's now available here it will show that. It's only a visual thing and doesn't effect usability.
