### ISSUE TITLE
Do we release a v0.5 version of MSM?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-settings-manager#58]
Do we release a v0.5 version? Also we should check how we package it. I'm for split-packages so we might have a **manjaro-settings-manager-kcm** or so.

**Comment by Kirek** [comment]
Yes, a split package would be better.
For the package without the kcm modules, kmcutils and kconfigwidgets dependency should be dropped.
The new notifier should be checked for non-kde DE thought.

**Comment by philmmanjaro** [comment]
Can you modify the **PKGBUILD** so we have these split packages? Testing shouldn't be an issue.

**Comment by philmmanjaro** [comment]
By installing **kcm-msm** into a **XFCE edition** I've followed extra packages pulled in:
```
Packages (37) attica-qt5-5.21.0-1  gpgmepp-16.04.0-1  karchive-5.21.0-1
              kauth-5.21.0-1  kbookmarks-5.21.0-1  kcmutils-5.21.0-1
              kcodecs-5.21.0-1  kcompletion-5.21.0-1  kconfig-5.21.0-1
              kconfigwidgets-5.21.0-1  kcoreaddons-5.21.0-1  kcrash-5.21.0-1
              kdbusaddons-5.21.0-1  kdeclarative-5.21.0-1
              kglobalaccel-5.21.0-1  kguiaddons-5.21.0-1  ki18n-5.21.0-1
              kiconthemes-5.21.0-1  kio-5.21.0-1  kitemviews-5.21.0-1
              kjobwidgets-5.21.0-1  knotifications-5.21.0-1  kpackage-5.21.0-1
              kservice-5.21.0-1  ktextwidgets-5.21.0-1  kwallet-5.21.0-1
              kwidgetsaddons-5.21.0-1  kwindowsystem-5.21.0-1  kxmlgui-5.21.0-1
              libdbusmenu-qt5-0.9.3+15.10.20150604-3
              manjaro-settings-manager-0.4.14-2 [removal]  phonon-qt5-4.9.0-1
              phonon-qt5-gstreamer-4.9.0-1  polkit-qt5-0.112.0+git20160226-1
              solid-5.21.0-1  sonnet-5.21.0-1  kcm-msm-0.4.95.r454.3e4776c-1

Total Installed Size:  81.84 MiB
Net Upgrade Size:      79.27 MiB
```
We might need to check which of these are needed ...

**Comment by Kirek** [comment]
This is mostly kcmutils (and kio) fault, I just made a split package https://github.com/manjaro/manjaro-settings-manager/commit/efb9ee379e9b852d94d9325987181de5d6de1ff9

**Comment by philmmanjaro** [comment]
Ok, I saw it. I already uploaded a new package to our **unstable** branch. The notifier works so far for **XFCE**...
