### ISSUE TITLE
Manjaro-settings-manager don't follow icon theme

### ISSUE THREAD

**Issue by scachemaille** [manjaro/manjaro-settings-manager#59]
is it possible that manjaro-settings-manager follow the desktop icon theme?

![screenshot_20160426_092041](https://cloud.githubusercontent.com/assets/16231972/14809968/d2e8d108-0b90-11e6-8ef2-61fbcbc790fd.png)
![screenshot_20160426_092133](https://cloud.githubusercontent.com/assets/16231972/14809971/d685e22e-0b90-11e6-9f0e-1ae9dd6e834d.png)
Screenshot with Theme icon
![screenshot_20160426_092204](https://cloud.githubusercontent.com/assets/16231972/14809973/d8961c0a-0b90-11e6-85fa-c1c8de94c7ba.png)

**Comment by philmmanjaro** [comment]
Do you refer to the **v.0.4.9x** releases of **msm**?

**Comment by scachemaille** [comment]
Yes, V.04.95-3
This morning on unstable I got an update where msm-kcm were replaced by manjaro-settings-manager-kcm, so I did some test.

**Comment by scachemaille** [comment]
I forked the project and will try to implement it. and will propose my modifications if it's ok for you,

**Comment by philmmanjaro** [comment]
Sure, go ahead. We will review it. Any improvement is welcome.

**Comment by Kirek** [comment]
Fixed via https://github.com/manjaro/manjaro-settings-manager/pull/62
