### ISSUE TITLE
Check if there is a way to reduce KF5 dependencies of MSM base package

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-settings-manager#61]
As of now **MSM** needs for example **kconfigwidgets** as dependency:
```
/usr/bin/manjaro-settings-manager-gui: error while loading shared libraries: libKF5ConfigWidgets.so.5: cannot open shared object file: No such file or directory
```
We have currently a lot of user complains who are not using **KDE** as their desktop ...

**Comment by Kirek** [comment]
Ok, I will take a look, maybe we need a notifier without knotifications too.

**Comment by Kirek** [comment]
KConfigWidgets dependency removed from "core" msm
https://github.com/manjaro/manjaro-settings-manager/commit/efa4652814fc5a1721720dccf2883b61a6471b5d
It's tested too.

**Comment by korrode** [comment]
Is this right Ramon...?

http://paradoxcomputers.com.au/images/msm_lots_deps_sadface.jpg

**Comment by philmmanjaro** [comment]
@korrode, yes. We are using now some KF5 dependencies.

**Comment by Kirek** [comment]
With the latest changes this should be much better for non KDE environment. 
What is left its unlikely to be removed (e.g. kauth).
