### ISSUE TITLE
MSM recommends to upgrade to a newer kernel even there is any

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-settings-manager#64]
I just got a recommendation to upgrade my 4.6 kernel to a newer kernel series :smile:

**Comment by Kirek** [comment]
https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git
you're welcome :sunglasses:

**Comment by philmmanjaro** [comment]
Exactly - I've to try, really.

**Comment by Kirek** [comment]
Can you check if this fixes it?
https://github.com/manjaro/manjaro-settings-manager/commit/72ce8241dc3187ff176b5378dd731627c7b0c2e5

**Comment by Kirek** [comment]
Should be solved in https://github.com/manjaro/manjaro-settings-manager/commit/4014a2a73969316522216e60060706d30ab42025
