### ISSUE TITLE
[msm-notifier] : Notifications settings can't work

### ISSUE THREAD

**Issue by scachemaille** [manjaro/manjaro-settings-manager#65]
If we set/change the notifications settings in manjaro-settings-mananger, 
msm_notifier don't know about these changes and will always use the default one.
As manjaro-settings-manager is launched as root the saved settings are in root home directory
but the notifier run as user and don't use the saved settings. 
the best solution would be to remove notification settings editor from the manager and add it in the notifier.

**Comment by scachemaille** [comment]
@Kirek 
The fix you talk about 
```
QSettings settings("/root/.config/manjaro/manjaro-settings-manager.conf",
                        QSettings::IniFormat);
```
it's a quick dirty fix for the functionality works. but In my opinion it should be a user setting as not all user want to receive notification or the same notification.

**Comment by Kirek** [comment]
I know, but is there a way to know which user started manjaro-settings-manager with root privileges?

Also the aim is to make msm not require root, like the kcm modules, but until the issue with kauth timeout is solved I leaved the old method in msm_bin.

**Comment by philmmanjaro** [comment]
@scachemaille: if you find some better solution, why not. Create a branch on your own fork, test it and create another pull request so we can review it. If we are happy with your work in general, why not join the team. @Kirek: what do you think about that? does @scachemaille fit to your code style already?

**Comment by scachemaille** [comment]
I propose as quick fix the following in msm_bin as it run as root:
`QSettings settings(QSettings::SystemScope, "manjaro", "manjaro-settings-manager");`
that mean it will read and write in the system wide patch ( I don't know where exactly)
and like as the notifier can't find settings in home directory it will fall back to system path.
and for kde it will stay in user home all the time. and the settings in home always overide the system settings.

what do you think about?
because the other fix would need to be done in the notifier with a deamon who can access without password to the root config file.

**Comment by Kirek** [comment]
The system wide is /etc/xdg
Basically this will only change the place we place the config, from root account to /etc, the problem will be the same.
I prefer the dirty fix until msm don't need to be run as root, really. (I prefer this because there will be two daemon, one for kde, without hacks, and another for the others DE).
A user daemon can read read root account files without problems afaik.

**Comment by scachemaille** [comment]
to put the config file in system patch with manaro-setting-manager who need to run as root for now for some reason. and to also put in system path in kcmodule with kauth would not be more easy?
as the notifier will be able to read this config file wihtout hack (just to force the SystemScope) in case an old user config exist.

to be coherent in all DE. I think it's the easier. otherwise it would need to kauth the kcmodule and a deamon for the 2 notifier.

**Comment by scachemaille** [comment]
hmm. I can tell you that if the daemon in the actual version is stable repos don't read the config file in root account. but take the default value given as fallback.

I don't see any easy solution without too much hacking because even kauth isn't easy as we can't use Qsetting with dbus.

the easiest would be to remove the notifications setitings from msm-settings.manager and  let the msm_notifier manage them in read/write

**Comment by Kirek** [comment]
You're right.

> the easiest would be to remove the notifications settings from msm-settings-manager and let the msm_notifier manage them in read/write 
probably this is the best way

**Comment by scachemaille** [comment]
#68 fix the issue.
the settings are now managed by the notifier, there is no more issue with mixing root and user
