### ISSUE TITLE
New release requirement

### ISSUE THREAD

**Issue by prescott66** [manjaro/manjaro-settings-manager#71]
Please can you release new 0.4.x version? Major translation updates was made.
Hope to see it in Manjaro soon :wink:

**Comment by Kirek** [comment]
Ok, I will try to make a new release this weekend.

**Comment by prescott66** [comment]
thanks

**Comment by Kirek** [comment]
A new release is now in the unstable repos.
https://github.com/manjaro/packages-extra/commit/689319f2d3f925c19766db66d14d2ba753bbb079

**Comment by prescott66** [comment]
thanks.hope to see it in stable soon ;-)
