### ISSUE TITLE
New line in icon name

### ISSUE THREAD

**Issue by prescott66** [manjaro/manjaro-settings-manager#72]
As you can see on screenshot, slovakian translation of some icons are too long. Can i use new line "\n" in icon names? For example: "Nastavenia**\n**klávesnice"

![screenshot-msm](https://cloud.githubusercontent.com/assets/735265/16919988/1bc374b6-4d0c-11e6-90b3-bc74fb4e4f8e.png)

**Comment by Kirek** [comment]
Investigated the issue a little, changed the behaviour of the icon text so it automatically uses multiple lines to display text if it doesn't fit, you don't need to use new line.

**Comment by prescott66** [comment]
perfect. so new release again? :smile:
