### ISSUE TITLE
Untranslated Notifier window

### ISSUE THREAD

**Issue by prescott66** [manjaro/manjaro-settings-manager#74]
I am testing new MSM release from Unstable repo and i have issue with Manjaro Notifier Settings window. There are all items untranslated, but all resources for Slovak are translated in sources-transifex.
Main Manjaro settings manager window is OK - fully translated.

**Comment by scachemaille** [comment]
fixed in 1a3b764a13f4fda7144246f12837fac8ad672e04 and 80f4547776db176c9c0db4b19d7e06c55f6ecb07
