### ISSUE TITLE
[KCModule] Translation problem

### ISSUE THREAD

**Issue by scachemaille** [manjaro/manjaro-settings-manager#78]
There is some place in the KCM modules that are not translated but are in the manjaro-settings-manager.
I don't understand why.
![screenshot_20160720_105631](https://cloud.githubusercontent.com/assets/16231972/16981032/1e785e98-4e69-11e6-911e-0a51f898d8ec.png)
![screenshot_20160720_105817](https://cloud.githubusercontent.com/assets/16231972/16981041/260857d0-4e69-11e6-9c94-33e12cb77872.png)

and also in all dialogs

**Comment by scachemaille** [comment]
I found why in the keyboard module. (fixed and will commit later).

**Comment by Kirek** [comment]
Really weird, in some modules some things get translated and others not...
