### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by prescott66** [manjaro/manjaro-settings-manager#79]
As you can see on screesnhots, i get some layout problems on my HP Mini(Screen size: 10.1"  Resolution: 1024x576).
MSM version: 0.4.97-3

1.)Maximize button dont work - window is not maximized
2.)On screen is not visible bottom of the window, where is buton "All settings"
3.)Color of window is black - i dont know, if is it bug or function :smile: 

![scrnshot1](https://cloud.githubusercontent.com/assets/735265/17064832/dc5ccb34-503e-11e6-9d04-112e96cc1d82.png)
![scrnshot2](https://cloud.githubusercontent.com/assets/735265/17064833/dc5ef9e0-503e-11e6-9131-c327b9b73d0f.png)

**Comment by scachemaille** [comment]
I think the maximize don't work because the minimum height is bigger than the screen.

**Comment by prescott66** [comment]
i had similar problems with Pamac.it was fixed few months ago.

**Comment by scachemaille** [comment]
for the black color. it have to be related with the theme for root.

**Comment by scachemaille** [comment]
@kirek 
I tried to change the size policy to ignore of the stackedWidget to be able to resize verticaly and activate the scroll bar.
just wanted to know. is it better to change both (verticaly and horizontaly) or just verticaly?

**Comment by Kirek** [comment]
Not sure what is better, should be fine with both.

**Comment by prescott66** [comment]
Layout looks fine now. Only little issue as you can see on screenshot, buttons are unnecessarily big
![scrnshot3](https://cloud.githubusercontent.com/assets/735265/17078426/2f553d30-50f3-11e6-9bd6-aa80826bde34.png)

**Comment by philmmanjaro** [comment]
@prescott66: please use a working design and configure your box right. We have that issue with**qt 5.7** and we already posted a working solution. What you see is a theme issue.

**Comment by prescott66** [comment]
Here are another modules. It looks like fixes for this issue makes more problems...
![hp](https://cloud.githubusercontent.com/assets/735265/17078459/de66f502-50f3-11e6-960c-8f50b4c760b3.png)
![keyboard](https://cloud.githubusercontent.com/assets/735265/17078460/e509c1e6-50f3-11e6-9f17-ff21e264fb96.png)
![lang](https://cloud.githubusercontent.com/assets/735265/17078461/e5922d6a-50f3-11e6-9c7e-c3863da0e1e0.png)
![Uploading time.png…]()

**Comment by philmmanjaro** [comment]
@prescott66: I don't get your problem. [Please fix](https://github.com/manjaro/release-plan/issues/73) your **qt5 theming**. We have a guide for that. This is how it looks if you have fixed it:

![msm1](https://cloud.githubusercontent.com/assets/5050022/17078476/7468b310-50f4-11e6-8763-d30b30df37ae.png)

![msm2](https://cloud.githubusercontent.com/assets/5050022/17078479/79e3dc66-50f4-11e6-9734-1e2fbbd16b25.png)

![msm3](https://cloud.githubusercontent.com/assets/5050022/17078480/80700474-50f4-11e6-8e58-78b2400bd2ad.png)

Remember you start the **manjaro-settings-manager** with **root-rights**. Therefore you have also to configure that account.

**Comment by philmmanjaro** [comment]
Please start **MSM** from a terminal. If you have configured it right it should give you following output:

```
[phil@manjaro manjaro-settings-manager]$ manjaro-settings-manager
using qt5ct plugin
Shutting down Manjaro Settings Manager...
```

**Comment by prescott66** [comment]
When i use command "manjaro-settings-manager using qt5ct plugin" MSM looks fine...

**Comment by Kirek** [comment]
Then the problem may be in the gtk version of the desktop file, does starting "manjaro-settings-manager -style=gtk" produce the same problems?

**Comment by prescott66** [comment]
"manjaro-settings-manager -style=gtk" produces same problem

**Comment by Kirek** [comment]
Removed launcher with -style=gtk https://github.com/manjaro/manjaro-settings-manager/commit/400a3ea98f26ea81e7570d0697af740435234184

**Comment by philmmanjaro** [comment]
@prescott66: as I already mentioned. Either copy the configuration also to the **root** user or start **qt5ct** as root and configure again.
