### ISSUE TITLE
Segfault when opening hardware detection

### ISSUE THREAD

**Issue by mirh** [manjaro/manjaro-settings-manager#84]
`segfault at 8 ip 00007f6a64bb6475 sp 00007ffe6a0111a0 error 4 in libQt5Widgets.so.5.7.0[7f6a649a0000+627000]`

Dump and stack [here](http://www101.zippyshare.com/v/RyHpTo4j/file.html).

**Comment by philmmanjaro** [comment]
What is the version of the package? I've tested **manjaro-settings-manager 0.4.98-7** on my **Nvidia** system and all is fine with it.

**Comment by mirh** [comment]
Same version, but I get crashes on my AMD laptop.

**Comment by philmmanjaro** [comment]
Open it from a terminal and post the full output of the crash.

**Comment by mirh** [comment]
Terminal just mentions "line 14". 
If you want more stuff, I uploaded everything above (dumb github don't let me attach zip here)

**Comment by philmmanjaro** [comment]
well, you can use **gist** or **pastebin** to display a text file better. The question is if it is a profile issue or a general issue on your end. Maybe recompile the package and check if that is fixing your issue.

**Comment by mirh** [comment]
[Here you are](http://pastebin.com/9BLWMpzi). 
And coredump as I said is [here](http://www101.zippyshare.com/v/RyHpTo4j/file.html).

**Comment by mirh** [comment]
[Updated](https://github.com/manjaro/manjaro-settings-manager/files/560705/crash.7z.txt). 
Now for some reason, UI even shows up. 

Crash happens as soon as I try to use any element though.

**Comment by mirh** [comment]
It's better now (ie: you can scroll up and down). 
But it still crashes after some seconds. 

`0x00007ffff6ace9f5 in QPixmapStyle::drawCheckBox(QStyleOption const*, QPainter*, QWidget const*) const ()    from /usr/lib/libQt5Widgets.so.5`

[Core dump](https://github.com/manjaro/manjaro-settings-manager/files/659514/core.manjaro-setting.1000.d5e7065d0829456aa0916686eba2bf60.989.1482073901000000000000.lz4.zip.txt)

**Comment by mirh** [comment]
Just tried latest released 0.5.0-2.. and it works!
