### ISSUE TITLE
manjaro-settings-manager-notifier was not installed during system upgrade.

### ISSUE THREAD

**Issue by crocket** [manjaro/manjaro-settings-manager#85]
I noticed it only because I installed manjaro on a new machine.
On a new machine, in XFCE4 settings, I found `Manjaro Notifier Settings`.
On the old machine, there is no `Manjaro Notifier Settings` in XFCE4 settings.

Why did this happen?

**Comment by scachemaille** [comment]
Because they are now optional and there is 2 different packages. One using only qt notifications
And the second one using intoxication (kde).
It should say it as comment during install skit the optional package

**Comment by crocket** [comment]
Thanks for the information. However, I can't read the output of `pacman -Syu` or pamac every time I upgrade.

**Comment by scachemaille** [comment]
I understand. there was some changes in the packaging. and there was no easy solution to "install/update" the notifier as now there is 2 packages. they both not conflict with the other, but only one is needed as they have the same functionality.  I don't say it was impossible just that it was not worth it, ;)
